
name: CI

on: [push]

jobs:
  test:
    name: Test, Build & Upload

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.1-rc
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: 📥 Checkout git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ☕ Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 💼 Load Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 🛠 Build jars 
        run: |
          cd Plan
          ./gradlew shadowJar
      - name: ⚙ Get versions
        run: |
          cd Plan
          ./gradlew snapshotVersion jarNameVersion
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=$(cat build/versions/snapshot.txt)" >> $GITHUB_ENV
          echo "versionString=$(cat build/versions/jar.txt)" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: 📤 Upload PlanFabric.jar 
        uses: actions/upload-artifact@v3
        with:
          name: PlanFabric-${{ env.versionString }}-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/PlanFabric-${{ env.snapshotVersion }}.jar
